### PR TITLE
Expo 47 and React 18 Upgrade

### PR DESCRIPTION
**Pull request by shafique17z**
# Type of PR

- [x] Improvement (_improving an existing feature - includes `style:` and `perf:`commits_)
# Description

The project was using an outdated expo version 45 but I upgraded it to 47. Along with that, I also updated React to version 18.

### **Changes**

Only frontend/package.json file needed changes because this is where older versions of Expo and React were declared.

## Additional information/context

On Expo Go app -- run your app by manually typing out the your ip address and port number. For example; exp://192.168.10.1:19000.

### CODE REVIEW

**Comment by Kinostrome** [comment]
@shafique17z this new PR doesn't seem to address the issues mentioned in the thread of your original PR #22. As you can see, tests are still failing.

Could you please incorporate the fixes provided by @starjustice in #24?

It'd be great to have your PR be the one that lands in this repo. @starjustice was just providing some support on some of the issues that came up, so we'll close his PR once yours has resolved the remaining issues.

By the way thanks for fixing the `expo r -c` command—as that produces a pretty weird error if you don't know what's causing it.

**Comment by shafique17z** [comment]
I actually deleted my previous PR as it contained unnecessary wild changes but fixed them in this new PR. Can please try to re-build and run it again as it works fine on my side!?

I'm also gonna look into @starjustice branch and will incorporate his changes into mine.

And you're welcome for the `expo r -c ` fix.

Thanks x.

**Comment by Kinostrome** [comment]
@shafique17z it appears the checks are still failing.

We have temporarily disabled the restriction on first-time contributors to run actions on the repo. Now your changes should re-run by default (only new Github users are restricted).

In CI, it appears that the `yarn generate` step (which is crucial to running the project) is failing due to a type error. If you run this locally, you should be able to reproduce the error that is appearing on Github Actions.

Alternatively, #24 is passing, so you may want to sync with those changes again before committing.

Once this PR is passing these checks, we can merge it in.

**Comment by Kinostrome** [comment]
@shafique17z are you able to fix this so that we could merge it in? Would be great to land your changes.

**Comment by SimonBiggs** [comment]
> @shafique17z are you able to fix this so that we could merge it in? Would be great to land your changes.

If it helps @Kinostrome, I have merged in these, as well as the current alpha-v2 branch, and iterated until all the tests pass over in the following PR:

https://github.com/lexiconhq/lexicon/pull/36

**Comment by Kinostrome** [comment]
> > @shafique17z are you able to fix this so that we could merge it in? Would be great to land your changes.
> 
> If it helps @Kinostrome, I have merged in these, as well as the current `alpha-v2` branch, and iterated until all the tests pass over in the following PR:
> 
> #36


Thanks for the help on getting this unblocked @SimonBiggs. We ended up merging @starjustice's PR to the v1 branch.

**Comment by Kinostrome** [comment]
> # Type of PR
> * [x]  Improvement (_improving an existing feature - includes `style:` and `perf:`commits_)
> 
> # Description
> The project was using an outdated expo version 45 but I upgraded it to 47. Along with that, I also updated React to version 18.
> 
> ### **Changes**
> Only frontend/package.json file needed changes because this is where older versions of Expo and React were declared.
> 
> ## Additional information/context
> On Expo Go app -- run your app by manually typing out the your ip address and port number. For example; exp://192.168.10.1:19000.

Thanks again for your work on this @shafique17z. Since it has been a while and other users were looking to make use of these changes, we merged @starjustice's branch (derived from yours) which had the tests passing.

**Pull request closed without merging**
