### PR TITLE
Update react native version

### PR DESCRIPTION
**Pull request by SimonBiggs**
# Type of PR

- [ ] Bug fix (_non-breaking change which fixes an issue_)
- [ ] New feature (_adding a feature following a feature-request issue_)
- [x] Improvement (_improving an existing feature - includes `style:` and `perf:`commits_)
- [ ] Refactor (_rewriting existing code without any feature change_)
- [ ] (!) This change is or requires a documentation update

# Description

Expo provided the following warning message:

```
[1] Some dependencies are incompatible with the installed expo version:
[1]   react-native@0.69.6 - expected version: 0.69.9
[1] Your project may not work correctly until you install the correct versions of the packages.
[1] Install individual packages by running npx expo install react-native@0.69.9
```

### **Changes**

Ran `npx expo install react-native@0.69.9` as per expo message

### CODE REVIEW

**Comment by SimonBiggs** [comment]
@Kinostrome, is this formatting okay?

**Review by starjustice — APPROVED** [review]
Hey @SimonBiggs, thank you for making the necessary changes for the React Native update. We missed incorporating this update when attempting to push updates to the alpha-v2 branch. Once this PR is merged, we will proceed to push the new update to the alpha-v2 branch.

**Comment by SimonBiggs** [comment]
> Once this PR is merged, we will proceed to push the new update to the alpha-v2 branch.

Brilliant thank you. I don't myself have merging permission, so that will need to be done on your end.

**Comment by Kinostrome** [comment]
> @Kinostrome, is this formatting okay?

Yes, thanks for fixing the issue. There is still a missing "type of PR". As I mentioned it's important to always fill out the template fully. In this case I have filled that one out for you.

**Pull request merged**
