### PR TITLE
Improve Chinese Language Support & Fix Issue with Asset File Names

### PR DESCRIPTION
**Pull request by Bardreamaster**
# Type of PR

- [x] Bug fix (_non-breaking change which fixes an issue_)
- [ ] New feature (_adding a feature following a feature-request issue_)
- [x] Improvement (_improving an existing feature - includes `style:` and `perf:`commits_)
- [ ] Refactor (_rewriting existing code without any feature change_)
- [ ] (!) This change is or requires a documentation update

# Description

0. Fix asset import error caused by name in lower case.
1. Fix Simplified Chinese keywords for `getPosterTypeDetails` .

### **Changes**

<details>
<summary>Assets name</summary>

Fix asset import issue by renaming the following files:

- frontend/assets/icons/adminPanel.svg → frontend/assets/icons/AdminPanel.svg
- frontend/assets/icons/settings.svg → frontend/assets/icons/Settings.svg
</details>

## **Additional Screenshots**

Nope.

## Additional information/context

Tested on Discourse site in Chinese. (https://forum.robook.org)

### CODE REVIEW

**Comment by Kinostrome** [comment]
Hi @Bardreamaster thanks for your contribution and for improving the i18n support.

Could you explain a bit more about the asset renaming issue? We haven't ever encountered that, and would need more details to accept it as a change. For this reason, it can sometimes be better to break up PRs into sets of changes, so that, for example, the i18n PR doesn't get blocked by a separate issue.

**Comment by Bardreamaster** [comment]
@Kinostrome Sorry for forgetting the problem description.

And in `fronted APP`, the icons be imported using capitalized filename in [frontend/src/icons.ts](
https://github.com/lexiconhq/lexicon/blob/a80c05c03bb1f86dd96b2d3b8ed12ee6c239b036/frontend/src/icons.ts#L3C52-L3C52)：

``` ts
import Admin from '../assets/icons/AdminPanel.svg';
```
```ts
import Settings from '../assets/icons/Settings.svg';
```

But the filename is [lowercase](https://github.com/lexiconhq/lexicon/blob/alpha-v2/frontend/assets/icons/adminPanel.svg). So it causes error on fronted APP:
```
Unable to resolve module
``` 

So we have to unify naming to avoid import error.

**Comment by Kinostrome** [comment]
> @Kinostrome Sorry for forgetting the problem description.
> 
> And in `fronted APP`, the icons be imported using capitalized filename in [frontend/src/icons.ts](https://github.com/lexiconhq/lexicon/blob/a80c05c03bb1f86dd96b2d3b8ed12ee6c239b036/frontend/src/icons.ts#L3C52-L3C52)：
> 
> ```ts
> import Admin from '../assets/icons/AdminPanel.svg';
> ```
> 
> ```ts
> import Settings from '../assets/icons/Settings.svg';
> ```
> 
> But the filename is [lowercase](https://github.com/lexiconhq/lexicon/blob/alpha-v2/frontend/assets/icons/adminPanel.svg). So it causes error on fronted APP:
> 
> ```
> Unable to resolve module
> ```
> 
> So we have to unify naming to avoid import error.

Got it, that's exactly what we needed. That is indeed an issue, thanks for fixing it.

**Comment by Kinostrome** [comment]
Hey @Bardreamaster, could you push a whitespace commit to your branch on your fork? Our CI checks weren't configured to run for `alpha-v2`. Now they are, and we just need the checks to get triggered for your branch so they'll run.

**Pull request closed without merging**
