### PR TITLE
Fix "edit this page" link at the bottom of docs

### PR DESCRIPTION
**Pull request by SimonBiggs**
# Type of PR
- [x] Bug fix (_non-breaking change which fixes an issue_)

# Description

The edit link on the documentation site does not work. When you click on it, it takes you to Github with a white screen which just says "Not found".

### **Changes**

This PR fixes the edit link for all of the documentation so that it includes the branch and takes users to the correct file.

## **Additional Screenshots**

N/A

## Additional information/context

N/A

### CODE REVIEW

**Review by Kinostrome — APPROVED** [review]
Hey! Thanks for catching this and fixing it. Appreciate the contribution.

**Comment by Kinostrome** [comment]
One side note—for future reference, please don't erase the PR template when submitting a PR, even if it's for something small. We'd appreciate it if you would please take a moment to fill it out before submitting. In this case, I went ahead and filled it out for you.

Thanks again for the fix.

**Comment by SimonBiggs** [comment]
Did you would me to also contribute a PR to have these docs build with GitHub pages?

It appears that currently the docs aren't re-building to match what is in the main branch (current docs still point to the old URL):

image

**Comment by Kinostrome** [comment]
> Did you would me to also contribute a PR to have these docs build with GitHub pages?
> 
> It appears that currently the docs aren't re-building to match what is in the main branch (current docs still point to the old URL):
> 
> image

Yes, this is intentional. We deliberately deploy the docs manually and internally, and we have several significant changes to the documentation coming up.

**Pull request merged**
