### PR TITLE
Fix Upgrade expo react native Type

### PR DESCRIPTION
**Pull request by starjustice**
# Type of PR

- [x] Bug fix (_non-breaking change which fixes an issue_)
- [ ] New feature (_adding a feature following a feature-request issue_)
- [ ] Improvement (_improving an existing feature - includes `style:` and `perf:`commits_)
- [ ] Refactor (_rewriting existing code without any feature change_)
- [ ] (!) This change is or requires a documentation update

# Description

- This PR fix all type error from PR #22 for expo-image-picker and react-native-markdown-display
- add config eslint because eslint-kodefox-config package already outdated

### **Changes**

<details>
<summary>Date: Monday, 10 Apr 2023</summary>

#### **Contextual Changes:**

- change type `ImagePickerResult` cancelled to canceled
- change how to get uri in `ImagePickerResult` using assets
- add children type for react-native-markdown-display based on issue https://github.com/iamacup/react-native-markdown-display/issues/181

</details>

<details>
<summary>Date: Wed, 12 Apr 2023</summary>

#### **Contextual Changes:**

- add new eslint config in file `.eslintrc.json`
- add new devDep for eslint 
  - `@typescript-eslint/eslint-plugin`
  - `@typescript-eslint/parser`
  - `eslint-config-prettier`
  - `eslint-plugin-eslint-comments`
  - `eslint-plugin-prettier`
  - `eslint-plugin-react`
  - `eslint-plugin-react-hooks`
  - `eslint-plugin-react-native`
  - `eslint-plugin-styles`
  - `eslint-plugin-t`
- Change new typescript version

</details>

## **Additional Screenshots**

Provide screenshot if necessary.

## Additional information/context

_If relevant, add any information or context that would be useful to evaluate this PR_

### CODE REVIEW

**Comment by Kinostrome** [comment]
Hey @bonsaibauer, give this branch a try.

There is a separate outstanding issue being worked on related to certain image upload URLs (you would see an error message in dev mode like "upload://3j21k1l...") from specific posts. We're hoping to get to the bottom of that one relatively soon.

**Comment by bonsaibauer** [comment]
Yarn test run/NPM test run was successful, no issues, thank you very much!

I am confused about all the warnings regarding "has unmet per dependency." What are the implications of these warnings?

**Comment by starjustice** [comment]
> * I am confused about all the warnings regarding "has unmet per dependency." What are the implications of these warnings?

Hey, @bonsaibauer, thank you for testing these changes.

Regarding the warnings about "unmet peer dependencies," This should not be an issue for you. This warning occurs when a package being installed has peer dependencies that are not installed or are not satisfied with the installed versions.

In general, a dependency is a library or package that your project needs to run, while a peer dependency is used to indicate a library or package that your project will hook into.

In this case, the warnings are showing because some packages are still using older versions of peer dependencies. However, some of these packages, such as react-native-keyboard-accessory, are already compatible with Expo. I don't think there will be any errors or issues when trying to use these packages in the app.

As for some dev packages like graphql-codegen, they should not cause any issues for the app. This package is only used to generate GraphQL types from the API, which can be used in the frontend code.

**Comment by bonsaibauer** [comment]
Thank you for the detailed and understandable explanation. I'm glad I could help, and there are several aspects that I now understand.

**Comment by SimonBiggs** [comment]
Hi @starjustice,

Do you happen to know if this PR is planned for merging?

**Review by Kinostrome — APPROVED** [review]
This seems fine to improve some of the issues with v1

**Comment by starjustice** [comment]
> Hi @starjustice and @Kinostrome,
> 
> Do you happen to know if this PR is planned for merging?
> 
> I can confirm, that using the master branch I was unable to even load up the Lexicon app within an Android emulator. However, using this PR, I was able to load up the app within the emulator.

hey @SimonBiggs,

I will merge this PR. And thanks for your work on PR #36 to try to fix the issue in the master branch to make the app works.

**Comment by SimonBiggs** [comment]
> And thanks for your work on PR https://github.com/lexiconhq/lexicon/pull/36

My pleasure, thank you for all your work building this brilliant Discourse app :)

**Pull request merged**
